twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    
    # Variables globales disponibles dans tous les templates
    globals:
        app_name: 'SOMAFI - Gestion Parc'
        agencies: '%app.agencies%'

when@dev:
    twig:
        debug: true
        strict_variables: true

when@test:
    twig:
        strict_variables: true
