framework:
    validation:
        email_validation_mode: html5
        
        # Active la validation par attributs PHP
        enable_attributes: true

when@test:
    framework:
        validation:
            not_compromised_password: false
